# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: marketplace
spec:
  owner: ${{values.owner | dump}}
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-clean-code
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    github.com/actions-workflow: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}/actions
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: marketplace
  providesApis: [api1, api2, api3]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api1
spec:
  type: http
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: marketplace
  definition: |
    openapi: "3.0.0"
    info:
      title: "API 1"
      version: "1.0.0"
    paths:
      /api1:
        get:
          summary: "Endpoint for API 1"
          responses:
            '200':
              description: "Successful response"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api2
spec:
  type: http
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: marketplace
  definition: |
    openapi: "3.0.0"
    info:
      title: "API 2"
      version: "1.0.0"
    paths:
      /api2:
        get:
          summary: "Endpoint for API 2"
          responses:
            '200':
              description: "Successful response"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api3
spec:
  type: http
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: marketplace
  definition: |
    openapi: "3.0.0"
    info:
      title: "API 3"
      version: "1.0.0"
    paths:
      /api3:
        get:
          summary: "Endpoint for API 3"
          responses:
            '200':
              description: "Successful response"
